---
# tasks file for ansible-pacman

- name: "Install packages defined in pacman_packages"
  become: true
  pacman:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  loop: "{{ pacman_packages }}"
  when: pacman_packages|default([])|count > 0